`ifndef TCDS2_HEADER_H
`define TCDS2_HEADER_H

localparam C_TCDS2_FRAME_WIDTH_10G = 234;
localparam C_TCDS2_TTS2_VALUE_WIDTH = 8;
localparam C_TCDS2_TTS2_NUM_VALUES = 14;
localparam C_TCDS2_TTS2_VALUES_WIDTH = C_TCDS2_TTS2_NUM_VALUES * C_TCDS2_TTS2_VALUE_WIDTH;

`endif
