create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 6 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list apex_blk_w/apex_blk_i/clk_wiz/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {serial_io/drpm/drpdo_fpga[0]} {serial_io/drpm/drpdo_fpga[1]} {serial_io/drpm/drpdo_fpga[2]} {serial_io/drpm/drpdo_fpga[3]} {serial_io/drpm/drpdo_fpga[4]} {serial_io/drpm/drpdo_fpga[5]} {serial_io/drpm/drpdo_fpga[6]} {serial_io/drpm/drpdo_fpga[7]} {serial_io/drpm/drpdo_fpga[8]} {serial_io/drpm/drpdo_fpga[9]} {serial_io/drpm/drpdo_fpga[10]} {serial_io/drpm/drpdo_fpga[11]} {serial_io/drpm/drpdo_fpga[12]} {serial_io/drpm/drpdo_fpga[13]} {serial_io/drpm/drpdo_fpga[14]} {serial_io/drpm/drpdo_fpga[15]} {serial_io/drpm/drpdo_fpga[16]} {serial_io/drpm/drpdo_fpga[17]} {serial_io/drpm/drpdo_fpga[18]} {serial_io/drpm/drpdo_fpga[19]} {serial_io/drpm/drpdo_fpga[20]} {serial_io/drpm/drpdo_fpga[21]} {serial_io/drpm/drpdo_fpga[22]} {serial_io/drpm/drpdo_fpga[23]} {serial_io/drpm/drpdo_fpga[24]} {serial_io/drpm/drpdo_fpga[25]} {serial_io/drpm/drpdo_fpga[26]} {serial_io/drpm/drpdo_fpga[27]} {serial_io/drpm/drpdo_fpga[28]} {serial_io/drpm/drpdo_fpga[29]} {serial_io/drpm/drpdo_fpga[30]} {serial_io/drpm/drpdo_fpga[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {serial_io/drpm/drpdi_quad[1][0]} {serial_io/drpm/drpdi_quad[1][1]} {serial_io/drpm/drpdi_quad[1][2]} {serial_io/drpm/drpdi_quad[1][3]} {serial_io/drpm/drpdi_quad[1][4]} {serial_io/drpm/drpdi_quad[1][5]} {serial_io/drpm/drpdi_quad[1][6]} {serial_io/drpm/drpdi_quad[1][7]} {serial_io/drpm/drpdi_quad[1][8]} {serial_io/drpm/drpdi_quad[1][9]} {serial_io/drpm/drpdi_quad[1][10]} {serial_io/drpm/drpdi_quad[1][11]} {serial_io/drpm/drpdi_quad[1][12]} {serial_io/drpm/drpdi_quad[1][13]} {serial_io/drpm/drpdi_quad[1][14]} {serial_io/drpm/drpdi_quad[1][15]} {serial_io/drpm/drpdi_quad[1][16]} {serial_io/drpm/drpdi_quad[1][17]} {serial_io/drpm/drpdi_quad[1][18]} {serial_io/drpm/drpdi_quad[1][19]} {serial_io/drpm/drpdi_quad[1][20]} {serial_io/drpm/drpdi_quad[1][21]} {serial_io/drpm/drpdi_quad[1][22]} {serial_io/drpm/drpdi_quad[1][23]} {serial_io/drpm/drpdi_quad[1][24]} {serial_io/drpm/drpdi_quad[1][25]} {serial_io/drpm/drpdi_quad[1][26]} {serial_io/drpm/drpdi_quad[1][27]} {serial_io/drpm/drpdi_quad[1][28]} {serial_io/drpm/drpdi_quad[1][29]} {serial_io/drpm/drpdi_quad[1][30]} {serial_io/drpm/drpdi_quad[1][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {serial_io/drpm/drpdi_fpga[0]} {serial_io/drpm/drpdi_fpga[1]} {serial_io/drpm/drpdi_fpga[2]} {serial_io/drpm/drpdi_fpga[3]} {serial_io/drpm/drpdi_fpga[4]} {serial_io/drpm/drpdi_fpga[5]} {serial_io/drpm/drpdi_fpga[6]} {serial_io/drpm/drpdi_fpga[7]} {serial_io/drpm/drpdi_fpga[8]} {serial_io/drpm/drpdi_fpga[9]} {serial_io/drpm/drpdi_fpga[10]} {serial_io/drpm/drpdi_fpga[11]} {serial_io/drpm/drpdi_fpga[12]} {serial_io/drpm/drpdi_fpga[13]} {serial_io/drpm/drpdi_fpga[14]} {serial_io/drpm/drpdi_fpga[15]} {serial_io/drpm/drpdi_fpga[16]} {serial_io/drpm/drpdi_fpga[17]} {serial_io/drpm/drpdi_fpga[18]} {serial_io/drpm/drpdi_fpga[19]} {serial_io/drpm/drpdi_fpga[20]} {serial_io/drpm/drpdi_fpga[21]} {serial_io/drpm/drpdi_fpga[22]} {serial_io/drpm/drpdi_fpga[23]} {serial_io/drpm/drpdi_fpga[24]} {serial_io/drpm/drpdi_fpga[25]} {serial_io/drpm/drpdi_fpga[26]} {serial_io/drpm/drpdi_fpga[27]} {serial_io/drpm/drpdi_fpga[28]} {serial_io/drpm/drpdi_fpga[29]} {serial_io/drpm/drpdi_fpga[30]} {serial_io/drpm/drpdi_fpga[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 10 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 10 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 5 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drprdy_quad[0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drprdy_quad[1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drprdy_quad[2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drprdy_quad[3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drprdy_quad[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 10 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 5 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpen_quad[0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpen_quad[1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpen_quad[2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpen_quad[3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpen_quad[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 10 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 10 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 13 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {serial_io/drpm/drpaddr_quad[1][0]} {serial_io/drpm/drpaddr_quad[1][1]} {serial_io/drpm/drpaddr_quad[1][2]} {serial_io/drpm/drpaddr_quad[1][3]} {serial_io/drpm/drpaddr_quad[1][4]} {serial_io/drpm/drpaddr_quad[1][5]} {serial_io/drpm/drpaddr_quad[1][6]} {serial_io/drpm/drpaddr_quad[1][7]} {serial_io/drpm/drpaddr_quad[1][8]} {serial_io/drpm/drpaddr_quad[1][9]} {serial_io/drpm/drpaddr_quad[1][10]} {serial_io/drpm/drpaddr_quad[1][11]} {serial_io/drpm/drpaddr_quad[1][12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 32 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][9]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][10]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][11]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][12]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][13]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][14]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][15]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][16]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][17]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][18]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][19]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][20]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][21]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][22]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][23]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][24]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][25]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][26]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][27]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][28]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][29]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][30]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[4][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 32 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][9]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][10]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][11]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][12]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][13]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][14]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][15]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][16]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][17]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][18]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][19]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][20]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][21]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][22]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][23]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][24]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][25]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][26]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][27]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][28]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][29]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][30]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[4][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[9]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[10]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[11]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[12]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[13]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[14]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[15]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[16]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[17]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[18]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[19]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[20]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[21]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[22]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[23]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[24]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[25]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[26]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[27]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[28]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[29]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[30]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_fpga[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 32 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][9]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][10]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][11]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][12]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][13]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][14]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][15]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][16]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][17]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][18]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][19]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][20]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][21]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][22]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][23]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][24]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][25]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][26]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][27]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][28]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][29]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][30]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[1][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 32 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][9]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][10]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][11]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][12]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][13]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][14]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][15]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][16]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][17]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][18]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][19]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][20]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][21]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][22]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][23]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][24]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][25]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][26]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][27]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][28]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][29]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][30]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[2][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 5 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/int_reg_quad[0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/int_reg_quad[1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/int_reg_quad[2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/int_reg_quad[3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/int_reg_quad[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 32 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][9]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][10]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][11]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][12]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][13]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][14]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][15]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][16]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][17]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][18]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][19]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][20]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][21]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][22]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][23]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][24]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][25]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][26]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][27]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][28]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][29]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][30]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[3][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 13 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_fpga[0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_fpga[1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_fpga[2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_fpga[3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_fpga[4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_fpga[5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_fpga[6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_fpga[7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_fpga[8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_fpga[9]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_fpga[10]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_fpga[11]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpaddr_fpga[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 32 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][9]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][10]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][11]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][12]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][13]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][14]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][15]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][16]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][17]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][18]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][19]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][20]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][21]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][22]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][23]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][24]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][25]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][26]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][27]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][28]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][29]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][30]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdo_quad[0][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 5 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpwe_quad[0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpwe_quad[1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpwe_quad[2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpwe_quad[3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpwe_quad[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 32 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[9]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[10]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[11]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[12]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[13]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[14]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[15]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[16]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[17]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[18]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[19]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[20]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[21]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[22]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[23]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[24]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[25]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[26]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[27]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[28]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[29]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[30]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_fpga[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 32 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][9]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][10]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][11]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][12]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][13]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][14]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][15]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][16]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][17]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][18]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][19]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][20]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][21]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][22]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][23]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][24]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][25]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][26]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][27]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][28]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][29]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][30]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[4][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 32 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][9]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][10]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][11]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][12]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][13]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][14]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][15]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][16]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][17]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][18]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][19]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][20]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][21]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][22]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][23]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][24]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][25]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][26]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][27]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][28]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][29]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][30]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[2][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 32 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][9]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][10]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][11]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][12]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][13]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][14]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][15]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][16]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][17]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][18]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][19]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][20]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][21]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][22]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][23]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][24]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][25]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][26]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][27]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][28]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][29]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][30]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[3][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 32 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {serial_io/drpm/drpdi_quad[0][0]} {serial_io/drpm/drpdi_quad[0][1]} {serial_io/drpm/drpdi_quad[0][2]} {serial_io/drpm/drpdi_quad[0][3]} {serial_io/drpm/drpdi_quad[0][4]} {serial_io/drpm/drpdi_quad[0][5]} {serial_io/drpm/drpdi_quad[0][6]} {serial_io/drpm/drpdi_quad[0][7]} {serial_io/drpm/drpdi_quad[0][8]} {serial_io/drpm/drpdi_quad[0][9]} {serial_io/drpm/drpdi_quad[0][10]} {serial_io/drpm/drpdi_quad[0][11]} {serial_io/drpm/drpdi_quad[0][12]} {serial_io/drpm/drpdi_quad[0][13]} {serial_io/drpm/drpdi_quad[0][14]} {serial_io/drpm/drpdi_quad[0][15]} {serial_io/drpm/drpdi_quad[0][16]} {serial_io/drpm/drpdi_quad[0][17]} {serial_io/drpm/drpdi_quad[0][18]} {serial_io/drpm/drpdi_quad[0][19]} {serial_io/drpm/drpdi_quad[0][20]} {serial_io/drpm/drpdi_quad[0][21]} {serial_io/drpm/drpdi_quad[0][22]} {serial_io/drpm/drpdi_quad[0][23]} {serial_io/drpm/drpdi_quad[0][24]} {serial_io/drpm/drpdi_quad[0][25]} {serial_io/drpm/drpdi_quad[0][26]} {serial_io/drpm/drpdi_quad[0][27]} {serial_io/drpm/drpdi_quad[0][28]} {serial_io/drpm/drpdi_quad[0][29]} {serial_io/drpm/drpdi_quad[0][30]} {serial_io/drpm/drpdi_quad[0][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 32 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[9]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[10]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[11]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[12]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[13]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[14]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[15]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[16]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[17]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[18]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[19]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[20]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[21]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[22]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[23]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[24]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[25]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[26]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[27]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[28]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[29]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[30]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_fpga[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 32 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {serial_io/drpm/drpdo_quad[0][0]} {serial_io/drpm/drpdo_quad[0][1]} {serial_io/drpm/drpdo_quad[0][2]} {serial_io/drpm/drpdo_quad[0][3]} {serial_io/drpm/drpdo_quad[0][4]} {serial_io/drpm/drpdo_quad[0][5]} {serial_io/drpm/drpdo_quad[0][6]} {serial_io/drpm/drpdo_quad[0][7]} {serial_io/drpm/drpdo_quad[0][8]} {serial_io/drpm/drpdo_quad[0][9]} {serial_io/drpm/drpdo_quad[0][10]} {serial_io/drpm/drpdo_quad[0][11]} {serial_io/drpm/drpdo_quad[0][12]} {serial_io/drpm/drpdo_quad[0][13]} {serial_io/drpm/drpdo_quad[0][14]} {serial_io/drpm/drpdo_quad[0][15]} {serial_io/drpm/drpdo_quad[0][16]} {serial_io/drpm/drpdo_quad[0][17]} {serial_io/drpm/drpdo_quad[0][18]} {serial_io/drpm/drpdo_quad[0][19]} {serial_io/drpm/drpdo_quad[0][20]} {serial_io/drpm/drpdo_quad[0][21]} {serial_io/drpm/drpdo_quad[0][22]} {serial_io/drpm/drpdo_quad[0][23]} {serial_io/drpm/drpdo_quad[0][24]} {serial_io/drpm/drpdo_quad[0][25]} {serial_io/drpm/drpdo_quad[0][26]} {serial_io/drpm/drpdo_quad[0][27]} {serial_io/drpm/drpdo_quad[0][28]} {serial_io/drpm/drpdo_quad[0][29]} {serial_io/drpm/drpdo_quad[0][30]} {serial_io/drpm/drpdo_quad[0][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 32 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[9]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[10]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[11]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[12]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[13]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[14]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[15]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[16]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[17]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[18]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[19]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[20]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[21]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[22]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[23]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[24]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[25]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[26]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[27]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[28]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[29]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[30]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_fpga[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 2 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {serial_io/drpm/drprdy_quad[0]} {serial_io/drpm/drprdy_quad[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 2 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list {serial_io/drpm/drpen_quad[0]} {serial_io/drpm/drpen_quad[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 32 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list {serial_io/drpm/drpdo_quad[1][0]} {serial_io/drpm/drpdo_quad[1][1]} {serial_io/drpm/drpdo_quad[1][2]} {serial_io/drpm/drpdo_quad[1][3]} {serial_io/drpm/drpdo_quad[1][4]} {serial_io/drpm/drpdo_quad[1][5]} {serial_io/drpm/drpdo_quad[1][6]} {serial_io/drpm/drpdo_quad[1][7]} {serial_io/drpm/drpdo_quad[1][8]} {serial_io/drpm/drpdo_quad[1][9]} {serial_io/drpm/drpdo_quad[1][10]} {serial_io/drpm/drpdo_quad[1][11]} {serial_io/drpm/drpdo_quad[1][12]} {serial_io/drpm/drpdo_quad[1][13]} {serial_io/drpm/drpdo_quad[1][14]} {serial_io/drpm/drpdo_quad[1][15]} {serial_io/drpm/drpdo_quad[1][16]} {serial_io/drpm/drpdo_quad[1][17]} {serial_io/drpm/drpdo_quad[1][18]} {serial_io/drpm/drpdo_quad[1][19]} {serial_io/drpm/drpdo_quad[1][20]} {serial_io/drpm/drpdo_quad[1][21]} {serial_io/drpm/drpdo_quad[1][22]} {serial_io/drpm/drpdo_quad[1][23]} {serial_io/drpm/drpdo_quad[1][24]} {serial_io/drpm/drpdo_quad[1][25]} {serial_io/drpm/drpdo_quad[1][26]} {serial_io/drpm/drpdo_quad[1][27]} {serial_io/drpm/drpdo_quad[1][28]} {serial_io/drpm/drpdo_quad[1][29]} {serial_io/drpm/drpdo_quad[1][30]} {serial_io/drpm/drpdo_quad[1][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 5 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/int_reg_quad[0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/int_reg_quad[1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/int_reg_quad[2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/int_reg_quad[3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/int_reg_quad[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 32 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][9]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][10]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][11]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][12]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][13]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][14]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][15]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][16]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][17]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][18]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][19]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][20]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][21]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][22]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][23]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][24]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][25]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][26]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][27]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][28]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][29]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][30]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[0][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 5 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpwe_quad[0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpwe_quad[1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpwe_quad[2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpwe_quad[3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpwe_quad[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 10 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[3][9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 10 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[2][9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 10 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[4][9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 2 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list {serial_io/drpm/int_reg_quad[0]} {serial_io/drpm/int_reg_quad[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 2 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list {serial_io/drpm/drpwe_quad[0]} {serial_io/drpm/drpwe_quad[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 32 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][9]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][10]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][11]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][12]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][13]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][14]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][15]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][16]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][17]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][18]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][19]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][20]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][21]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][22]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][23]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][24]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][25]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][26]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][27]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][28]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][29]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][30]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[0][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 32 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][9]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][10]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][11]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][12]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][13]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][14]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][15]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][16]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][17]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][18]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][19]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][20]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][21]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][22]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][23]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][24]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][25]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][26]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][27]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][28]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][29]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][30]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdi_quad[1][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 10 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[1][9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 5 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drprdy_quad[0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drprdy_quad[1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drprdy_quad[2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drprdy_quad[3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drprdy_quad[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property port_width 10 [get_debug_ports u_ila_0/probe44]
connect_debug_port u_ila_0/probe44 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_quad[0][9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property port_width 32 [get_debug_ports u_ila_0/probe45]
connect_debug_port u_ila_0/probe45 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][9]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][10]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][11]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][12]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][13]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][14]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][15]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][16]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][17]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][18]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][19]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][20]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][21]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][22]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][23]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][24]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][25]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][26]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][27]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][28]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][29]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][30]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[1][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property port_width 13 [get_debug_ports u_ila_0/probe46]
connect_debug_port u_ila_0/probe46 [get_nets [list {serial_io/drpm/drpaddr_quad[0][0]} {serial_io/drpm/drpaddr_quad[0][1]} {serial_io/drpm/drpaddr_quad[0][2]} {serial_io/drpm/drpaddr_quad[0][3]} {serial_io/drpm/drpaddr_quad[0][4]} {serial_io/drpm/drpaddr_quad[0][5]} {serial_io/drpm/drpaddr_quad[0][6]} {serial_io/drpm/drpaddr_quad[0][7]} {serial_io/drpm/drpaddr_quad[0][8]} {serial_io/drpm/drpaddr_quad[0][9]} {serial_io/drpm/drpaddr_quad[0][10]} {serial_io/drpm/drpaddr_quad[0][11]} {serial_io/drpm/drpaddr_quad[0][12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe47]
set_property port_width 64 [get_debug_ports u_ila_0/probe47]
connect_debug_port u_ila_0/probe47 [get_nets [list {serial_io/drpm/quad_port_select_w[0]} {serial_io/drpm/quad_port_select_w[1]} {serial_io/drpm/quad_port_select_w[2]} {serial_io/drpm/quad_port_select_w[3]} {serial_io/drpm/quad_port_select_w[4]} {serial_io/drpm/quad_port_select_w[5]} {serial_io/drpm/quad_port_select_w[6]} {serial_io/drpm/quad_port_select_w[7]} {serial_io/drpm/quad_port_select_w[8]} {serial_io/drpm/quad_port_select_w[9]} {serial_io/drpm/quad_port_select_w[10]} {serial_io/drpm/quad_port_select_w[11]} {serial_io/drpm/quad_port_select_w[12]} {serial_io/drpm/quad_port_select_w[13]} {serial_io/drpm/quad_port_select_w[14]} {serial_io/drpm/quad_port_select_w[15]} {serial_io/drpm/quad_port_select_w[16]} {serial_io/drpm/quad_port_select_w[17]} {serial_io/drpm/quad_port_select_w[18]} {serial_io/drpm/quad_port_select_w[19]} {serial_io/drpm/quad_port_select_w[20]} {serial_io/drpm/quad_port_select_w[21]} {serial_io/drpm/quad_port_select_w[22]} {serial_io/drpm/quad_port_select_w[23]} {serial_io/drpm/quad_port_select_w[24]} {serial_io/drpm/quad_port_select_w[25]} {serial_io/drpm/quad_port_select_w[26]} {serial_io/drpm/quad_port_select_w[27]} {serial_io/drpm/quad_port_select_w[28]} {serial_io/drpm/quad_port_select_w[29]} {serial_io/drpm/quad_port_select_w[30]} {serial_io/drpm/quad_port_select_w[31]} {serial_io/drpm/quad_port_select_w[32]} {serial_io/drpm/quad_port_select_w[33]} {serial_io/drpm/quad_port_select_w[34]} {serial_io/drpm/quad_port_select_w[35]} {serial_io/drpm/quad_port_select_w[36]} {serial_io/drpm/quad_port_select_w[37]} {serial_io/drpm/quad_port_select_w[38]} {serial_io/drpm/quad_port_select_w[39]} {serial_io/drpm/quad_port_select_w[40]} {serial_io/drpm/quad_port_select_w[41]} {serial_io/drpm/quad_port_select_w[42]} {serial_io/drpm/quad_port_select_w[43]} {serial_io/drpm/quad_port_select_w[44]} {serial_io/drpm/quad_port_select_w[45]} {serial_io/drpm/quad_port_select_w[46]} {serial_io/drpm/quad_port_select_w[47]} {serial_io/drpm/quad_port_select_w[48]} {serial_io/drpm/quad_port_select_w[49]} {serial_io/drpm/quad_port_select_w[50]} {serial_io/drpm/quad_port_select_w[51]} {serial_io/drpm/quad_port_select_w[52]} {serial_io/drpm/quad_port_select_w[53]} {serial_io/drpm/quad_port_select_w[54]} {serial_io/drpm/quad_port_select_w[55]} {serial_io/drpm/quad_port_select_w[56]} {serial_io/drpm/quad_port_select_w[57]} {serial_io/drpm/quad_port_select_w[58]} {serial_io/drpm/quad_port_select_w[59]} {serial_io/drpm/quad_port_select_w[60]} {serial_io/drpm/quad_port_select_w[61]} {serial_io/drpm/quad_port_select_w[62]} {serial_io/drpm/quad_port_select_w[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe48]
set_property port_width 64 [get_debug_ports u_ila_0/probe48]
connect_debug_port u_ila_0/probe48 [get_nets [list {serial_io/drpm/quad_drp_select_w[0]} {serial_io/drpm/quad_drp_select_w[1]} {serial_io/drpm/quad_drp_select_w[2]} {serial_io/drpm/quad_drp_select_w[3]} {serial_io/drpm/quad_drp_select_w[4]} {serial_io/drpm/quad_drp_select_w[5]} {serial_io/drpm/quad_drp_select_w[6]} {serial_io/drpm/quad_drp_select_w[7]} {serial_io/drpm/quad_drp_select_w[8]} {serial_io/drpm/quad_drp_select_w[9]} {serial_io/drpm/quad_drp_select_w[10]} {serial_io/drpm/quad_drp_select_w[11]} {serial_io/drpm/quad_drp_select_w[12]} {serial_io/drpm/quad_drp_select_w[13]} {serial_io/drpm/quad_drp_select_w[14]} {serial_io/drpm/quad_drp_select_w[15]} {serial_io/drpm/quad_drp_select_w[16]} {serial_io/drpm/quad_drp_select_w[17]} {serial_io/drpm/quad_drp_select_w[18]} {serial_io/drpm/quad_drp_select_w[19]} {serial_io/drpm/quad_drp_select_w[20]} {serial_io/drpm/quad_drp_select_w[21]} {serial_io/drpm/quad_drp_select_w[22]} {serial_io/drpm/quad_drp_select_w[23]} {serial_io/drpm/quad_drp_select_w[24]} {serial_io/drpm/quad_drp_select_w[25]} {serial_io/drpm/quad_drp_select_w[26]} {serial_io/drpm/quad_drp_select_w[27]} {serial_io/drpm/quad_drp_select_w[28]} {serial_io/drpm/quad_drp_select_w[29]} {serial_io/drpm/quad_drp_select_w[30]} {serial_io/drpm/quad_drp_select_w[31]} {serial_io/drpm/quad_drp_select_w[32]} {serial_io/drpm/quad_drp_select_w[33]} {serial_io/drpm/quad_drp_select_w[34]} {serial_io/drpm/quad_drp_select_w[35]} {serial_io/drpm/quad_drp_select_w[36]} {serial_io/drpm/quad_drp_select_w[37]} {serial_io/drpm/quad_drp_select_w[38]} {serial_io/drpm/quad_drp_select_w[39]} {serial_io/drpm/quad_drp_select_w[40]} {serial_io/drpm/quad_drp_select_w[41]} {serial_io/drpm/quad_drp_select_w[42]} {serial_io/drpm/quad_drp_select_w[43]} {serial_io/drpm/quad_drp_select_w[44]} {serial_io/drpm/quad_drp_select_w[45]} {serial_io/drpm/quad_drp_select_w[46]} {serial_io/drpm/quad_drp_select_w[47]} {serial_io/drpm/quad_drp_select_w[48]} {serial_io/drpm/quad_drp_select_w[49]} {serial_io/drpm/quad_drp_select_w[50]} {serial_io/drpm/quad_drp_select_w[51]} {serial_io/drpm/quad_drp_select_w[52]} {serial_io/drpm/quad_drp_select_w[53]} {serial_io/drpm/quad_drp_select_w[54]} {serial_io/drpm/quad_drp_select_w[55]} {serial_io/drpm/quad_drp_select_w[56]} {serial_io/drpm/quad_drp_select_w[57]} {serial_io/drpm/quad_drp_select_w[58]} {serial_io/drpm/quad_drp_select_w[59]} {serial_io/drpm/quad_drp_select_w[60]} {serial_io/drpm/quad_drp_select_w[61]} {serial_io/drpm/quad_drp_select_w[62]} {serial_io/drpm/quad_drp_select_w[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe49]
set_property port_width 13 [get_debug_ports u_ila_0/probe49]
connect_debug_port u_ila_0/probe49 [get_nets [list {serial_io/drpm/drpaddr_fpga[0]} {serial_io/drpm/drpaddr_fpga[1]} {serial_io/drpm/drpaddr_fpga[2]} {serial_io/drpm/drpaddr_fpga[3]} {serial_io/drpm/drpaddr_fpga[4]} {serial_io/drpm/drpaddr_fpga[5]} {serial_io/drpm/drpaddr_fpga[6]} {serial_io/drpm/drpaddr_fpga[7]} {serial_io/drpm/drpaddr_fpga[8]} {serial_io/drpm/drpaddr_fpga[9]} {serial_io/drpm/drpaddr_fpga[10]} {serial_io/drpm/drpaddr_fpga[11]} {serial_io/drpm/drpaddr_fpga[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe50]
set_property port_width 32 [get_debug_ports u_ila_0/probe50]
connect_debug_port u_ila_0/probe50 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][9]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][10]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][11]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][12]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][13]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][14]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][15]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][16]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][17]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][18]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][19]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][20]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][21]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][22]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][23]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][24]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][25]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][26]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][27]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][28]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][29]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][30]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[3][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe51]
set_property port_width 32 [get_debug_ports u_ila_0/probe51]
connect_debug_port u_ila_0/probe51 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][0]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][1]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][2]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][3]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][4]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][5]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][6]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][7]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][8]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][9]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][10]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][11]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][12]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][13]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][14]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][15]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][16]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][17]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][18]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][19]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][20]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][21]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][22]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][23]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][24]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][25]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][26]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][27]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][28]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][29]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][30]} {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpdi_quad[2][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe52]
set_property port_width 5 [get_debug_ports u_ila_0/probe52]
connect_debug_port u_ila_0/probe52 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpen_quad[0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpen_quad[1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpen_quad[2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpen_quad[3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpen_quad[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe53]
set_property port_width 32 [get_debug_ports u_ila_0/probe53]
connect_debug_port u_ila_0/probe53 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][9]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][10]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][11]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][12]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][13]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][14]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][15]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][16]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][17]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][18]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][19]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][20]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][21]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][22]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][23]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][24]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][25]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][26]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][27]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][28]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][29]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][30]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[2][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe54]
set_property port_width 32 [get_debug_ports u_ila_0/probe54]
connect_debug_port u_ila_0/probe54 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][9]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][10]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][11]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][12]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][13]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][14]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][15]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][16]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][17]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][18]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][19]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][20]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][21]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][22]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][23]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][24]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][25]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][26]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][27]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][28]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][29]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][30]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[4][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe55]
set_property port_width 32 [get_debug_ports u_ila_0/probe55]
connect_debug_port u_ila_0/probe55 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][9]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][10]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][11]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][12]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][13]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][14]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][15]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][16]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][17]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][18]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][19]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][20]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][21]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][22]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][23]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][24]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][25]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][26]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][27]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][28]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][29]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][30]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[1][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe56]
set_property port_width 32 [get_debug_ports u_ila_0/probe56]
connect_debug_port u_ila_0/probe56 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][9]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][10]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][11]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][12]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][13]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][14]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][15]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][16]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][17]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][18]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][19]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][20]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][21]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][22]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][23]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][24]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][25]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][26]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][27]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][28]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][29]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][30]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[0][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe57]
set_property port_width 32 [get_debug_ports u_ila_0/probe57]
connect_debug_port u_ila_0/probe57 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][9]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][10]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][11]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][12]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][13]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][14]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][15]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][16]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][17]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][18]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][19]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][20]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][21]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][22]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][23]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][24]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][25]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][26]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][27]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][28]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][29]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][30]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpdo_quad[3][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe58]
set_property port_width 13 [get_debug_ports u_ila_0/probe58]
connect_debug_port u_ila_0/probe58 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_fpga[0]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_fpga[1]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_fpga[2]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_fpga[3]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_fpga[4]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_fpga[5]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_fpga[6]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_fpga[7]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_fpga[8]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_fpga[9]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_fpga[10]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_fpga[11]} {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpaddr_fpga[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe59]
set_property port_width 1 [get_debug_ports u_ila_0/probe59]
connect_debug_port u_ila_0/probe59 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpwe_fpga}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe60]
set_property port_width 1 [get_debug_ports u_ila_0/probe60]
connect_debug_port u_ila_0/probe60 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/int_reg_fpga}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe61]
set_property port_width 1 [get_debug_ports u_ila_0/probe61]
connect_debug_port u_ila_0/probe61 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drprdy_fpga}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe62]
set_property port_width 1 [get_debug_ports u_ila_0/probe62]
connect_debug_port u_ila_0/probe62 [get_nets [list serial_io/drpm/drpwe_fpga]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe63]
set_property port_width 1 [get_debug_ports u_ila_0/probe63]
connect_debug_port u_ila_0/probe63 [get_nets [list serial_io/drpm/drprdy_fpga]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe64]
set_property port_width 1 [get_debug_ports u_ila_0/probe64]
connect_debug_port u_ila_0/probe64 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpen_fpga}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe65]
set_property port_width 1 [get_debug_ports u_ila_0/probe65]
connect_debug_port u_ila_0/probe65 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drprdy_fpga}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe66]
set_property port_width 1 [get_debug_ports u_ila_0/probe66]
connect_debug_port u_ila_0/probe66 [get_nets [list {serial_io/quad_loop[1].GTYE4_QUAD_inst/drpm/drpen_fpga}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe67]
set_property port_width 1 [get_debug_ports u_ila_0/probe67]
connect_debug_port u_ila_0/probe67 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/int_reg_fpga}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe68]
set_property port_width 1 [get_debug_ports u_ila_0/probe68]
connect_debug_port u_ila_0/probe68 [get_nets [list {serial_io/quad_loop[0].GTYE4_QUAD_inst/drpm/drpwe_fpga}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe69]
set_property port_width 1 [get_debug_ports u_ila_0/probe69]
connect_debug_port u_ila_0/probe69 [get_nets [list serial_io/drpm/drpen_fpga]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets c2c_phy_clk]
