
# file: apex_gth_ibert.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_apex_gth_ibert.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT 7Series 
##**************************************************************************
##
## Icon Constraints
##

##gth_refclk lock constraints
##
set_property -dict {PACKAGE_PIN C31 IOSTANDARD LVDS} [get_ports fclkp]

set_property PACKAGE_PIN AG12 [get_ports gth_refclk0p_i[0]]
set_property PACKAGE_PIN AF10 [get_ports gth_refclk0p_i[1]]
set_property PACKAGE_PIN AA12 [get_ports gth_refclk0p_i[2]]
set_property PACKAGE_PIN Y10  [get_ports gth_refclk0p_i[3]]
set_property PACKAGE_PIN R12  [get_ports gth_refclk0p_i[4]]
set_property PACKAGE_PIN P10  [get_ports gth_refclk0p_i[5]]

set_property PACKAGE_PIN AD32 [get_ports gth_refclk0p_i[6]]
set_property PACKAGE_PIN AC30 [get_ports gth_refclk0p_i[7]]
set_property PACKAGE_PIN V32  [get_ports gth_refclk0p_i[8]]
set_property PACKAGE_PIN U30  [get_ports gth_refclk0p_i[9]]
set_property PACKAGE_PIN M32  [get_ports gth_refclk0p_i[10]]
set_property PACKAGE_PIN L30  [get_ports gth_refclk0p_i[11]]



##
## Refclk constraints
##
create_clock -name fclkp -period 3.1 [get_ports fclkp]
create_clock -name refclk0  -period 4.0 [get_ports gth_refclk0p_i[0]]
create_clock -name refclk1  -period 4.0 [get_ports gth_refclk0p_i[1]]
create_clock -name refclk2  -period 4.0 [get_ports gth_refclk0p_i[2]]
create_clock -name refclk3  -period 4.0 [get_ports gth_refclk0p_i[3]]
create_clock -name refclk4  -period 4.0 [get_ports gth_refclk0p_i[4]]
create_clock -name refclk5  -period 4.0 [get_ports gth_refclk0p_i[5]]
create_clock -name refclk6  -period 4.0 [get_ports gth_refclk0p_i[6]]
create_clock -name refclk7  -period 4.0 [get_ports gth_refclk0p_i[7]]
create_clock -name refclk8  -period 4.0 [get_ports gth_refclk0p_i[8]]
create_clock -name refclk9  -period 4.0 [get_ports gth_refclk0p_i[9]]
create_clock -name refclk10 -period 4.0 [get_ports gth_refclk0p_i[10]]
create_clock -name refclk11 -period 4.0 [get_ports gth_refclk0p_i[11]]

set_clock_groups -group [get_clocks fclkp    -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks refclk0  -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks refclk1  -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks refclk2  -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks refclk3  -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks refclk4  -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks refclk5  -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks refclk6  -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks refclk7  -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks refclk8  -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks refclk9  -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks refclk10 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks refclk11 -include_generated_clocks] -asynchronous
