create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 6 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list {c2c_gth_i/example_wrapper_inst/gtwiz_userclk_tx_inst/bbstub_txoutclk_out[1]}]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {c2c_gth_i/ch1_rxctrl2_int[0]} {c2c_gth_i/ch1_rxctrl2_int[1]} {c2c_gth_i/ch1_rxctrl2_int[2]} {c2c_gth_i/ch1_rxctrl2_int[3]} {c2c_gth_i/ch1_rxctrl2_int[4]} {c2c_gth_i/ch1_rxctrl2_int[5]} {c2c_gth_i/ch1_rxctrl2_int[6]} {c2c_gth_i/ch1_rxctrl2_int[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {c2c_gth_i/hb1_gtwiz_userdata_rx_int[0]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[1]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[2]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[3]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[4]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[5]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[6]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[7]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[8]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[9]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[10]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[11]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[12]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[13]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[14]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[15]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[16]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[17]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[18]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[19]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[20]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[21]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[22]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[23]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[24]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[25]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[26]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[27]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[28]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[29]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[30]} {c2c_gth_i/hb1_gtwiz_userdata_rx_int[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets drp_clk]
